version: "3"

vars:
  BUN: bun run --bun

tasks:
  next_dev:
    desc: "Development server for Next.js"
    cmds:
      - "{{.BUN}} next dev"

  next_build:
    desc: "Build Next.js project"
    cmds:
      - "{{.BUN}} next build"

  next_start:
    desc: "Start Next.js project"
    cmds:
      - "{{.BUN}} next start"

  next_lint:
    desc: "Lint Next.js project"
    cmds:
      - "{{.BUN}} next lint"

  format:
    desc: "Format code"
    cmds:
      - "{{.BUN}} dprint fmt"

  postinstall:
    desc: "Install app dependencies for Electron"
    cmds:
      - "{{.BUN}} electron-builder install-app-deps"

  electron_dist:
    desc: "Build Electron for distribution in directory mode"
    cmds:
      - "{{.BUN}} electron-builder --dir"

  electron_dist_deb:
    desc: "Build Electron for Debian distribution"
    cmds:
      - "{{.BUN}} electron-builder --linux deb"

  electron_build:
    desc: "Build Electron using tsup"
    cmds:
      - "{{.BUN}} tsup"

  build:
    desc: "Build both Next.js and Electron projects"
    cmds:
      - task next_build electron_build --parallel

  dist:
    desc: "Distribute both Next.js and Electron projects"
    cmds:
      - "task next_build && task electron_dist"

  dev:
    desc: "Development mode for both Electron and Next.js"
    cmds:
      - task next_dev electron_dev electron_build_watch --parallel
  electron_build_watch:
    desc: "Watch mode for Electron with tsup"
    cmds:
      - "{{.BUN}} tsup --watch"

  electron_dev:
    desc: "Development mode for Electron"
    cmds:
      - "{{.BUN}} cross-env NODE_ENV='development' nodemon"
